### ISSUE TITLE
Publish release with scalameta 4.0.0

### ISSUE THREAD

**Issue by ranchoiver** [twilio/guardrail#108]
scalameta 4.0.0 was released a month ago.
https://github.com/scalameta/scalameta/releases/tag/v4.0.0

Are there any blockers to publish `guardrail` with new version of `scalameta`?

**Comment by blast-hardcheese** [comment]
scalameta has been very good about maintaining their source API, so I don't expect there to be any problems. What's your use case? Dependency conflict with another plugin?
