### ISSUE TITLE
LocalDate type not supported in Api Client - missing implicit conversion

### ISSUE THREAD

**Issue by griffio** [twilio/guardrail#164]
Hi, We have a scenario where a request parameter is defined in the swagger spec as type
 string | date from https://swagger.io/specification/v2/#dataTypeFormat

When 💂🛤generates the code for the Client Api there is no implicit support for LocalDate - Server Api *is* supported and therefore the client doesn't compile.

This can be seen here - only date-time is supported
https://github.com/twilio/guardrail/blame/8ae7ecab6024a0e36b9d0569eda0a95048092f62/modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala#L177

Is there a reason why it would be not supported or has no-one needed it yet? 😸
Thanks!

**Comment by blast-hardcheese** [comment]
You're definitely the first to report it! The rest of the infrastructure[¹](https://github.com/twilio/guardrail/blob/8ae7ecab6024a0e36b9d0569eda0a95048092f62/modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala#L221-L222) [²](https://github.com/twilio/guardrail/blob/8ae7ecab6024a0e36b9d0569eda0a95048092f62/modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala#L105-L106) would seem to be in place, but another instance of `Show` would definitely need to be provided for `LocalDate`.

As a workaround, you can definitely do something like:
```scala
package com.example.client.hacks

import com.example.client.Implicits.Show

object LocalDateInstances {
    implicit val showLocalDate = build[java.time.LocalDate](_.format(java.time.format.DateTimeFormatter.ISO_LOCAL_DATE))
}
```

then modify your plugin config similar to [this build.sbt](https://github.com/blast-hardcheese/guardrail-version-isolation/blob/master/build.sbt#L26):
```scala
      Client(file("spec.yaml"), pkg="com.example.client", imports = List("com.example.client.hacks.LocalDateInstances._"))
```
