### ISSUE TITLE
Is it possible to just generate models by themselves from the swagger?

### ISSUE THREAD

**Issue by calvinbrown085** [twilio/guardrail#166]
I don't see a gitter room, so i'll make an issue and delete if there's a better place to ask :)

Is it possible to generate models by themselves with no client or server yet? 

If not is there a place I can place a feature request at? I'd be happy to contribute to help get there!

**Comment by blast-hardcheese** [comment]
You've done it!

I think the most straightforward way to implement this would be to add an additional `Kind`, then add an additional branch to https://github.com/twilio/guardrail/blob/master/modules/codegen/src/main/scala/com/twilio/guardrail/Common.scala#L97, and providing an empty `CodegenDefinitions` result

**Comment by calvinbrown085** [comment]
@blast-hardcheese Awesome! I'll for sure take a look at this! Thanks for pointing me in the right direction!
