### ISSUE TITLE
discriminator mapping

### ISSUE THREAD

**Issue by dsilvasc** [twilio/guardrail#193]
Thank you for adding support for OpenAPI 3.0.  Does this include support for the `mapping` field of a `discriminator`?

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#discriminator-object

I have an api where two different types have discriminators whose values overlap, so a mapping would resolve the clash.

This is the api in swagger 2.0:

```yaml
definitions:
  A:
    type: object
    discriminator: type
    properties:
      type:
        type: string
        enum:
          - X
          - Y
  B:
    type: object
    discriminator: type
    properties:
      type:
        type: string
        enum:
          - Y
          - Z
```

Notice that `Y` is a discriminator value for both `A` and `B`.  In Swagger 2.0 I wouldn't be able to define a Y for A and a Y for B -- the definition needs to be called Y, and there can only be one of those.  But in Swagger 3.0 that could be:

```yaml
definitions:
  A:
    type: object
    discriminator:
      propertyName: type
      mapping:
        X: AX
        Y: AY
    properties:
      type:
        type: string
        enum:
          - X
          - Y
  B:
    type: object
    discriminator:
      propertyName: type
      mapping:
        Y: BY
        Z: BZ
    properties:
      type:
        type: string
        enum:
          - Y
          - Z
  AY:
    allOf:
      - $ref: "#/definitions/A"
      - type: object
         properties:
           ...
  BY:
    allOf:
      - $ref: "#/definitions/B"
      - type: object
         properties:
           ...
```

**Comment by blast-hardcheese** [comment]
Unfortunately we have no support for `mapping` yet, though this is a very interesting use case!

We track literals separately from the underlying keys, so I actually think this may be straightforward to implement (check the generated Circe encoders and decoders for an example of this).

To get an idea of where this work would happen, look for places where `ScalaParameter` is built. Note the distinction between `param: L#MethodParameter` and `argName: RawParameterName`.
