### ISSUE TITLE
x-server-raw-response should be x-scala-raw-response

### ISSUE THREAD

**Issue by blast-hardcheese** [twilio/guardrail#196]
Currently, `x-server-raw-response` is the only extension that doesn't follow the `x-${language}` idiom.

Resolving this clears up confusion around other supported languages.

(Raised from #19)

**Comment by dsilvasc** [comment]
https://github.com/twilio/guardrail/pull/194

**Comment by dpblh** [comment]
Actually `x-server-raw-response` generate only server code :(

**Comment by blast-hardcheese** [comment]
@dpblh Considering #194, I think this can be closed -- what are you experiencing? I'm going to close for now, as the initial intent has been resolved, but we can continue to discuss or open other issues
