### ISSUE TITLE
reference to `identity` in generated `object Implicits` can conflict with a package name

### ISSUE THREAD

**Issue by dsilvasc** [twilio/guardrail#211]
The generated `object Implicits` contains [this line](https://github.com/twilio/guardrail/blob/159bb6e4b69cc6b275d34194e9c91be415eaed83/modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala#L169):

```scala
implicit val showString = build[String](identity)
```

When the generated code lives in a package foo.bar.baz and another package foo.identity exists in the classpath, the generated code fails to compile with:

```
Implicits.scala:21: package identity is not a value
    implicit val showString = build[String](identity)
```

I think that changing `identity` to `Predef.identity` would avoid the issue.

**Comment by blast-hardcheese** [comment]
Likely `_root_.Predef.identity`, but this just kicks the can down the road until someone needs to accept a property named `_root_`.

Still, not a bad workaround, for the time being. Constraining all bare identifiers would be a huge win, as far as I'm concerned.

I think the long-term solution would be to add `mapping`, a la #193 (or a language-specific workaround, like `x-scala-name`, permitting per-language workarounds for collisions)

Are you available to add this workaround to `identity`? I can likely cut a release either later today or tomorrow if so.

**Comment by dsilvasc** [comment]
Thank you for the quick reply.  Adding this in https://github.com/twilio/guardrail/pull/212
