### ISSUE TITLE
http4s classes not generated

### ISSUE THREAD

**Issue by tomasherman** [twilio/guardrail#219]
Hi, i've been trying guardrail but have hard time making it generate http4s classes. Here is the config and repo: https://github.com/tomasherman/guardrail-playground/blob/master/build.sbt

Am i doing it wrong?

no matter what i do i am getting akka-http

**Comment by blast-hardcheese** [comment]
Fixed in sbt-guardrail 0.45.2, my apologies!

**Comment by blast-hardcheese** [comment]
Feel free to reopen if necessary

**Comment by tomasherman** [comment]
thanks, it works well! also let me thank you for this project - we are strongly considering using it at work! currently we are blocked by #218 also but we really like the code it generates (http4s)
