### ISSUE TITLE
Support for UUID formatted Strings

### ISSUE THREAD

**Issue by SpyMachine** [twilio/guardrail#223]
I'd love to see support for Strings with the UUID format. Currently this fails for me with the following error:

`Error:Unknown type for the following structure (type: string, class: io.swagger.v3.oas.models.media.UUIDSchema):
  class UUIDSchema {
      class Schema {
      }
      type: string
      format: uuid
  }`

**Comment by blast-hardcheese** [comment]
Oh, definitely. I'm intrigued that swagger-parser had a `UUIDSchema`, despite `uuid` not being a valid format in [the specification](https://swagger.io/specification/#data-types).

As a quick workaround, you can use `x-scala-type: java.util.UUID`, providing your own instances of the required typeclasses (`Show`, `Decoder`) via `imports=List("com.example.hacks._")` in your build.sbt.

As for more permanent support, I'd [start here] (https://github.com/twilio/guardrail/blob/836034f95568df7991f1d57bbc24c172b9a68512/modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala#L240)

**Comment by SpyMachine** [comment]
Workaround works! Thanks! Except I had a create a custom `type` fur UUID 😆I also didn't have to create any custom typeclasses, I think the UUIDs might already be handled by http4s/circe for me.

```[error] /Users/gkuruc/Development/Guardrail/target/scala-2.12/src_managed/main/com/example/server/users/Routes.scala:29:10: overriding value UUIDVar in trait Http4sDsl of type org.http4s.dsl.impl.UUIDVar.type;
[error]  object UUIDVar needs `override' modifier
[error]   object UUIDVar {
[error]          ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 6 s, completed Apr 1, 2019 8:34:56 AM```
