### ISSUE TITLE
In Java builders, initialize optional List<> properties/parameters without Optional

### ISSUE THREAD

**Issue by kelnos** [twilio/guardrail#247]
Currently it looks like we do (in POJO and client call builders)
```java
private Optional<List<String>> foos = Optional.empty();

public Builder withFoos(final List<String> foos) {
    this.foos = Optional.of(foos);
}
```
Really we should just do
```java
private List<String> foos = Collections.emptyList();

public Builder withFoos(final List<String> foos) {
    this.foos = requireNonNull(foos);
}
```

**Comment by blast-hardcheese** [comment]
This is to enforce required parameters in the builders? 👍

**Comment by kelnos** [comment]
This ends up being a Jackson issue (though arguably it's behaving correctly/consistently).  If you have an `Optional<List<>>` property in a POJO that is `Optional.empty()`, you end up with a `null` for that property in the serialized JSON, which is probably never what you want.  The better approach is to just have a 'bare' `List<>` and initialize it to empty, which will end up as `[]` in the JSON.

From the perspective of the builder, the behavior and interface is the same.

**Comment by gisripa** [comment]
`.objectMapper(new ObjectMapper().setSerializationInclusion(JsonInclude.Include.NON_ABSENT))` this excluded Optional<SomeObject> values, guess it might work for List too.
