### ISSUE TITLE
Akka HttpEntity as response to GET request

### ISSUE THREAD

**Issue by gvince01** [twilio/guardrail#295]
Hi,

I'm writing an endpoint that returns a file. Instead of saving the file to disc, and then sending that file as a response, I’d like to respond to the request with an Akka `HttpEntity` (or similar). I was wondering if there is currently support for this. I'm using OpenAPI version 2, and sbt-guardrail 0.48

Thanks

**Comment by blast-hardcheese** [comment]
Currently this is not supported. Your best bet would be `~`-ing your guardrail routes with a fallback routing layer that does what you need.

One of the challenges we've been facing is that there's no way to know the order of `multipart/form-data` submissions. Consider:

```
curl whatever \
  -F foo=123 \
  -F bar="woop" \
  -F baz=@/tmp/file.tgz
```

All field processing can be handled before control is returned from the routing layer.

Compare that to:
```
curl whatever \
  -F bar="woop" \
  -F baz=@/tmp/file.tgz \
  -F foo="invalid data!"
```

There's no way to know that the fields are all valid before processing the file argument.

All that being said, an avenue we could take would be responding with a 400 if there are missing strict parameters before the submitted file. This strategy doesn't scale to two or more files though, as the second could be invalid.

If you have any thoughts of how you expected this would work, I'm interested to hear them!

**Comment by kelnos** [comment]
@gvince01 I have an item open (https://github.com/twilio/guardrail/issues/251) to use `InputStream` instead of `File` for Dropwizard file/binary data.  We should really do the same for akka-http etc. as well.  (Well, `InputStream` for request data, and `OutputStream` for response data.)  With that, you'd be able to do what you need.  (Alternatively, we could also use akka-streams' `Source[ByteStream, Any]` and `Sink[ByteStream, Any]`.)  But, unfortunately, until that work is done, this use case isn't supported; you have to write the file to disk first.

**Comment by gvince01** [comment]
@kelnos ah yes, I'm trying to avoid writing the file to disk, as it's just not practical in my use case. I think my next route of action is try what  @blast-hardcheese said above, namely:

> Your best bet would be ~-ing your guardrail routes with a fallback routing layer that does what you need.

@blast-hardcheese thanks for the response, I don't really have any thoughts about how I expected it to work unfortunately. I'd been looking at the Play framework, where they have `Action` and was hoping to emulate that.

**Comment by blast-hardcheese** [comment]
@gvince01 A cursory glance at https://www.playframework.com/documentation/2.7.x/ScalaFileUpload suggests that they do almost the exact same thing with [`TemporaryFile`](https://www.playframework.com/documentation/2.7.x/api/scala/play/api/libs/Files$$TemporaryFile.html), is there a streaming variant?
