### ISSUE TITLE
akka-http server generation does not support text/plain in the response body

### ISSUE THREAD

**Issue by kelnos** [twilio/guardrail#306]
With a `produces: text/plain` and `type: string` for the body parameter, the server sends back the string with a content-type of `application/json`.  The reason is in `AkkaHttpImplicits`: `implicit def jsonEntityMarshaller` will create an entity marshaller for JSON payloads as long as it sees an implicit circe `Encoder` in scope.  Since there's an `Encoder[String]` coming from somewhere, trying to `Marshal(aString).to[ResponseEntity]` will give you JSON.

I think we need to make use of the `TextPlain` wrapper, but `GenerateResponseDefinitions` doesn't have access to what the operation is supposed to produce, so it's not clear how to make the decision when emitting the definition.

**Comment by oswaldo** [comment]
I have the feeling that this is the kind of issue that silently makes everyone just use some workaround. In this case, a simple json response or not declare the path in the yaml used for generation and do it in custom code afterwards.
Just mentioning because I would be interested in seeing this one closed and probably other silent people would too ;)

**Comment by blast-hardcheese** [comment]
@oswaldo Turned out to be a relatively straight-forward change to thread the needed data through

**Comment by oswaldo** [comment]
@blast-hardcheese That is awesome. Didn't think that would be so quick. My thanks and congratulations to the team for this great project.

FYI I'm prototyping some services for an enterprise-grade solution where I'm evaluating sbt-guardrail as the tool to generate server and a couple of client-side modules.

So far all looks good despite a couple of workaroundable bugs. I'll look if I find open issues here about the 2 others I found. Hopefully, they are also quick fixes ;)
