### ISSUE TITLE
NPE when in body parameter schema is missing

### ISSUE THREAD

**Issue by sbrunk** [twilio/guardrail#309]
I'm trying to generate a client from the [spec](https://raw.githubusercontent.com/jupyterhub/jupyterhub/master/docs/rest-api.yml) of the [JupyterHub REST API](https://jupyterhub.readthedocs.io/en/stable/api/).

When I run guardrail I get the following NPE:

```
[error] java.lang.NullPointerException
[error]         at com.twilio.guardrail.terms.RouteMeta.$anonfun$extractRefParamFromRequestBody$2(SwaggerTerm.scala:86)
[error]         at scala.Option.flatMap(Option.scala:171)
[error]         at com.twilio.guardrail.terms.RouteMeta.$anonfun$extractRefParamFromRequestBody$1(SwaggerTerm.scala:85)
[error]         at scala.Option.flatMap(Option.scala:171)
[error]         at com.twilio.guardrail.terms.RouteMeta.extractRefParamFromRequestBody(SwaggerTerm.scala:84)
[error]         at com.twilio.guardrail.terms.RouteMeta.$anonfun$parameters$3(SwaggerTerm.scala:163)
[error]         at scala.Option.flatMap(Option.scala:171)
[error]         at com.twilio.guardrail.terms.RouteMeta.<init>(SwaggerTerm.scala:163)
[error]         at com.twilio.guardrail.generators.SwaggerGenerator$$anon$1.$anonfun$apply$5(SwaggerGenerator.scala:43)
[error]         at scala.collection.immutable.List.map(List.scala:282)
[error]         at com.twilio.guardrail.generators.SwaggerGenerator$$anon$1.$anonfun$apply$4(SwaggerGenerator.scala:38)
...
```

Here's a minimal version causing the issue. It seems to be the `type: boolean` not wrapped in a schema in combination with `in: body`. I'm not sure if this is even allowed in Swagger. In the examples body params are always wrapped (in contrast to header params).

```yaml
swagger: '2.0'
paths:
  /shutdown:
    post:
      summary: Shutdown the Hub
      operationId: shutdownHub
      parameters:
        - name: proxy
          in: body
          type: boolean # Causes the NPE
          # If you wrapp the type in a schema it works fine
          #schema:
          #  type: boolean
          description: Whether the proxy should be shutdown as well (default from Hub config)
      responses:
        200:
          description: ok
```

**Comment by sbrunk** [comment]
Turns out the error still happens if we remove the `type` field, i.e. having `in: body` without a schema.

**Comment by sbrunk** [comment]
The Swagger [spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object) says that `schema` is required in case of `in: body` 

If [`in`](#parameterIn) is `"body"`:

Field Name | Type | Description
---|:---:|---
<a name="parameterSchema"></a>schema | [Schema Object](#schemaObject) | **Required.** The schema defining the type used for the body parameter.

So this is clearly an invalid spec and I'll create a PR there.

I guess the one thing that might be useful here is a nicer error message instead of the NPE.

**Comment by blast-hardcheese** [comment]
Definitely. Thank you for the report!

https://github.com/twilio/guardrail/blob/97177754a7b88fa85c9a00609f2bdc1e5bbab800/modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerm.scala#L86

...clearly exposes the NPE. Unfortunately, this function has no way to report failure, so this'll need to move into a `SwaggerTerm` with a corresponding interpreter that fails with a useful message.

**Comment by kelnos** [comment]
This appears to have been fixed ad some point so there's no NPE in this situation; guardrail should just interpret it as not having a schema.
