### ISSUE TITLE
Question: Is it possible to use a custom scala type for query param, headers etc?

### ISSUE THREAD

**Issue by eli-jordan** [twilio/guardrail#331]
I'd like to use specific types for the path params, query params, headers etc to avoid getting them mixed up. I currently have methods that take up to 5 string arguments.

**Comment by blast-hardcheese** [comment]
@eli-jordan Currently we don't support plain value wrappers, though this is definitely on the roadmap.

**Comment by kelnos** [comment]
Yes, you can use `x-scala-type` (or `x-jvm-type` if it's usable in more than scala) in your OpenAPI spec file.  Depending on what it's used for, you'll also need to provide circe encoders/decoders and add `customImports` to your guardrail maven/sbt plugin configuration to bring them into scope.

**Comment by kelnos** [comment]
Actually I guess what you actually need are `Show[A]` implementations, if it's a client, and they're path/query/header params.

**Comment by eli-jordan** [comment]
Ok, I though I had tried this before and not had the scala types be present in the generated code. I just tried it again though, and they are there. So I must have done something wrong before. I'll see if I can define the right implicits to get it to work.

Thanks!

**Comment by kelnos** [comment]
@eli-jordan sorry... @blast-hardcheese and I chatted a bit offline about this.  You *can* do what I've suggested, but be careful and note that `Show` is a sort of guardrail implementation detail (which could change at any time in a future version), and also implementing `Show` (and using `x-scala-type`) is a bit of an escape hatch that can allow you to violate the contract you've specified in your OpenAPI spec, if you're not careful.  Please keep that in mind if you decide to go down that path.

**Comment by eli-jordan** [comment]
Ok thanks. I'll stick with the supported path for now :)
It looks like I need an implicit `AddArg` for a query parameter and `AddPath` for a path parameter.

**Comment by blast-hardcheese** [comment]
@eli-jordan You may get those for free if you implement `Show`, as @kelnos mentioned. Glad you were able to get a workable solution though!
