### ISSUE TITLE
Release binary artifacts

### ISSUE THREAD

**Issue by blast-hardcheese** [twilio/guardrail#37]
In preparation for releasing the sbt and Maven plugins, we should actually publish jars.

**Comment by manuelbernhardt** [comment]
@blast-hardcheese I'm writing an sbt plugin for guardrail -- it would be quite useful if the artifacts were published somewhere. Do you plan on doing this soon?

**Comment by ktoso** [comment]
Yeah would indeed help a lot :)
Let me know if you need any help (in case you're not familiar with the process getting an oss sonatype account etc etc)

Regarding the plugin, would it make sense to keep it here, close to the project?

**Comment by manuelbernhardt** [comment]
Okay so I've got a plugin that works locally with locally published sources. I expect there to be some quirks still and things that need fixing, and for the moment there's very little configuration options supported, but it's a start. It cross-compiles for sbt 1.0 and 0.13 and caches the compiled artifacts so the compilation doesn't get triggered every time. I pushed it [here](https://github.com/manuelbernhardt/sbt-guardrail) until we decide something.

> Regarding the plugin, would it make sense to keep it here, close to the project?

After giving this some thought I think this is up to @blast-hardcheese to decide, as integrating it in the core project means more maintenance work on the longer run (I should be able to help in the beginning but I don't know that I will be able to "monitor" the project on the long-term). If we go down that path I would try and find time to help with the integration in the coming week or the week after (kids don't leave much time for evening hacking). 

Need to run, my plane is boarding!

**Comment by blast-hardcheese** [comment]
@manuelbernhardt It took some time to get the repos set up, but I've got them now, as well as bintray access (🎉)

I was planning on releasing the internal sbt and maven plugins we have; lemme push up the code and any usability ideas you've got can be folded in, sound good?

**Comment by blast-hardcheese** [comment]
Alright. Binaries are now published under `Resolver.bintrayRepo("twilio", "releases")`, and [twilio/sbt-guardrail](https://github.com/twilio/sbt-guardrail) is now up (and published as well)

**Comment by blast-hardcheese** [comment]
Maven plugin has now also been released: [twilio/guardrail-maven-plugin](https://github.com/twilio/guardrail-maven-plugin)

**Comment by ktoso** [comment]
Awesome, thanks @blast-hardcheese :)
Do you think eventually they could be promoted to to maven central as well, or is it intentional to ask people to add a new repo with twilio in the name? (We publish such way, via bintray to maven central, so can share scripts to automate it if interested)

**Comment by manuelbernhardt** [comment]
Hi! Okay, that solves that :) Thanks!

**Comment by blast-hardcheese** [comment]
I expect it won't be a problem to also get the binaries published on other repositories, I'll see what I can do.

**Comment by ktoso** [comment]
Cool :)
