### ISSUE TITLE
Enum parsing/decoding of non-existing value

### ISSUE THREAD

**Issue by lorenzotomasini** [twilio/guardrail#414]
Hi all,

We are generating scala servers using guardrail and we are having some troubles when we use an Enum as request body parameter, in particular with the error handling.

we define the enum like this:

```
openapi: 3.0.0
info:
  title: Test Server
  version: "1.0"
servers:
  - url: http://localhost:8000
paths:
  /v1/Foo:
    post:
      summary: Test resource
      operationId: foo
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                Bar:
                  type: EnumName
                  description: An enum parameter
      responses:
        200:
          description: Ok
          content:
              text/plain:
                schema:
                  type: string
components:
  schemas:
    EnumName:
      type: string
      enum:
      - VALUE_1
      - VALUE_2
```

and when we try to pass a wrong value (`VALUE_3` for instance) we expect some sort of 4xx response but:
* if the parameter is not required, the request goes through and the parameter is set to `None` 
* otherwise, we get a 400 but with the wrong message: `Missing required form parameter 'EnumName'`

**Comment by blast-hardcheese** [comment]
That's quite unfortunate, which server generator are you using?

**Comment by lorenzotomasini** [comment]
We are using scala-generator

**Comment by blast-hardcheese** [comment]
@lorenzotomasini Sorry, I meant akka-http or http4s

**Comment by lorenzotomasini** [comment]
it was akka-http and for the records, this is fixed in the latest version
