### ISSUE TITLE
Current codegen files are not always emitted from WriteTree, causing SBT plugin to fail to compile

### ISSUE THREAD

**Issue by blast-hardcheese** [twilio/guardrail#422]
Introduced in #368, causing https://github.com/twilio/sbt-guardrail/issues/26. I'm opening a fix for it now, to be merged and immediately released in 0.54.1

**Comment by sbrunk** [comment]
I was just trying 0.54 and wondering why the compiler complains that the generated code doesn't exist, even though I can see it. I guess this could be the cause.

**Comment by blast-hardcheese** [comment]
@sbrunk Exactly that. It's annoying, but if you `git clean -fdx '*/target/scala-2.12/src_managed/*'` between builds you can at the very least continue to work until 0.54.1 drops. Sorry for the inconvenience.

**Comment by blast-hardcheese** [comment]
@sbrunk 0.54.1 has been released, sorry for the inconvenience!

**Comment by sbrunk** [comment]
Thanks for fixing it so fast!
