### ISSUE TITLE
Switch from `IndexedSeq` to `Vector`

### ISSUE THREAD

**Issue by blast-hardcheese** [twilio/guardrail#440]
Using `IndexedSeq` was a mistake made early on without really thinking of the ramifications. Seeing as most immediately receive the `IndexedSeq` and call `.toList` or `.toVector` on it in order to get instances for cats, I think this should change.

I don't think this should be done before #389, as it would be great to permit folk to `x-scala-type: IndexedSeq` to make migration easier.

This has been on my backlog for a while, just raising it for visibility and to get feedback.

**Comment by eli-jordan** [comment]
Would be nice if the collection type could be configured. Either globally through a cli option or locally in the swagger spec.

**Comment by blast-hardcheese** [comment]
Good call. That would enable people to backport themselves and switch over piecemeal. Maybe https://github.com/twilio/guardrail/issues/44#issuecomment-428362393?

**Comment by blast-hardcheese** [comment]
Resolved in 0.55.0
