### ISSUE TITLE
Changes in PR #435 to make FQDN for StausCodes breaks test in PR #434

### ISSUE THREAD

**Issue by hywelandrews** [twilio/guardrail#443]
The above two PRs appear to have been merged into master, although he second is breaking a test in the first: 

> Test that fully qualified names are used

`httpClient.fetch(req)({
             case org.http4s.Status.Ok(resp) =>
               F.map(getUserOkDecoder.decode(resp, strict = false).value.flatMap(F.fromEither))(GetUserResponse.Ok.apply)
             case resp =>
               F.raiseError(UnexpectedStatus(resp.status))
})`

`org.http4s.Status.Ok(resp)` should become `_root_.org.http4s.Status.Ok(resp)`, however I'm raising this issue to understand what problem existed by just using the FQDN for `org.http4s.Status.Ok`

**Comment by blast-hardcheese** [comment]
Please see #444, there were actually more problems than just that 😄

**Comment by blast-hardcheese** [comment]
Anyway, I'd appreciate if you verify that your issue is resolved in that PR, sorry to have impacted you. I'll likely merge tomorrow, once there has been enough time for reviews.

**Comment by hywelandrews** [comment]
@blast-hardcheese PR #444 will fix my issue (which was just a failing test), I'll raise questions about why we're appending `_root_` to the http4s namespace as well, as this is unclear to me. Thanks

**Comment by blast-hardcheese** [comment]
@hywelandrews It's entirely trying to find a balance between verbosity of generated code and permitting any object definitions in the OpenAPI specifications themselves.

A couple of examples:
- Attempting to explicitly name a type whose package starts with `io` may conflict with `scala.io` (the reason that OpenAPI imports in the guardrail codebase are all prefixed with `_root_`)
- Managing to define an in-scope value named `com` or `org` would cause all non-`_root_` prefixed class paths to fail to resolve

So, in closing, sorry for the noise back and forth, I think this'll end up settling down once we find a decent reduction in unexpected blocking errors for people trying to get up and running with existing specification files that cannot be easily changed to work around bugs in guardrail (see: [this reddit comment](https://www.reddit.com/r/scala/comments/cyezfs/ann_api4s_derive_scala_code_for_your_http_api/eyro52q/), for instance)
