### ISSUE TITLE
Warn if duplicate response codes are specified for a single endpoint

### ISSUE THREAD

**Issue by blast-hardcheese** [twilio/guardrail#446]
Related to #442 
The OpenAPI parser permits specifications with duplicate keys(!), meaning that:
```
        "responses": {
          "400": {
            "description": "Invalid ID supplied"
          },
          "404": {
            "description": "Pet not found"
          },
          "400": {
            "description": "Validation exception"
          }
        },
```
is valid. This creates surprising error messages from the compiler, where it should actually be a specification validation error.

**Comment by sullis** [comment]
I reviewed the [swagger-parser] library to understand how it handles duplicate JSON field names.

I opened a Draft PR in the swagger-parser repo:
https://github.com/swagger-api/swagger-parser/pull/1271

**Comment by sullis** [comment]
Swagger-Parser accepted my PR ( https://github.com/swagger-api/swagger-parser/pull/1271 )

Hopefully we will see a new release of swagger-parser soon :)

**Comment by blast-hardcheese** [comment]
@sullis 2.0.17 seems to have been released!

**Comment by sullis** [comment]
Please close this issue.  We already merged PR 518 
https://github.com/twilio/guardrail/pull/518

**Comment by sullis** [comment]
PR 557 upgrades Guardrail to Swagger-Parser 2.0.18:
https://github.com/twilio/guardrail/pull/557

Swagger-Parser 2.0.18 enables strict validation for YAML-based spec files:
https://github.com/swagger-api/swagger-parser/pull/1313
