### ISSUE TITLE
Http4sImplicits breaks with http4s version >= v0.21.0-RC1

### ISSUE THREAD

**Issue by aherrmann13** [twilio/guardrail#529]
as of 1/21 [http4s v0.21.0-RC1](https://http4s.org/changelog/) `Media` supertype of `Message` was added and the `EntityDecoder` trait was updated ([commit here](https://github.com/http4s/http4s/commit/31eaf8490d6aeca64d5235caef9dd0810faf3837)).  This broke `Http4sImplicits` generation [here](https://github.com/twilio/guardrail/blob/04dd2d4dbbe6ba1f4d7f934c37660c349afc2227/modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sGenerator.scala#L58).

I am happy to create a pull request if I get some guidance on how to generate different versions of `Http4sImplicits` based on the version of http4s the consumer is using.

**Comment by blast-hardcheese** [comment]
Hey @aherrmann13, sorry for the delay in response.

Keeping source compatibility with http4s has been a challenge, if you take a look at [COMPATIBILITY#http4s](https://github.com/twilio/guardrail/blob/master/COMPATIBILITY.md#http4s) you can see a basic compatibility matrix.

I think the most straightforward thing to do would be to make the change in the file you linked, run `runtimeScalaSuite` to confirm that it can compile and that the tests pass.

If you notice that none of the `RoundTrip` tests fail, it'd be particularly kind of you to write a test that exercises the new functionality.

**Comment by Peppi-Ressler** [comment]
Hi we`ve encountered this issue as well. What is current status of this issue please? Guardrail is now incompatible with http4s 0.21.0+. I am honestly little bit confused as in compatibility section is clearly stated that 0.21.0 is compatible. Thanks

**Comment by blast-hardcheese** [comment]
It looks like 0.21.x included multiple changes, #448 must have been adding support for a milestone or RC release. I think #544 finishes the job, and at that point 0.21.x would be fully supported. Sorry for the confusion, let me push that through.

**Comment by aherrmann13** [comment]
sorry for the late response, working for me now - thanks!

**Comment by blast-hardcheese** [comment]
Great news! Thanks for confirming!
