### ISSUE TITLE
Response headers

### ISSUE THREAD

**Issue by manuelbernhardt** [twilio/guardrail#53]
Given the following `response` definition:

        // ...
        "responses" : {
          "200" : {
            "description" : "foo",
            "headers" : {
              "version" : {
                "type" : "integer",
                "default" : 3
              }
            }
          }

The generated handler doesn't seem to include a way to set the header value. Is this a bug, or a missing feature? In case it is missing, any hints as to where to look for adding this would be welcome!

**Comment by blast-hardcheese** [comment]
As for implementation of this feature, the code is all currently localized in the [`AkkaHttpServerGenerator`](https://github.com/twilio/guardrail/blob/e8fbbf3fbd27660db32cfa36cae2f32de3e08e27/modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala#L154-L182).

Accumulating and then flattening a `List[Option[...]]`s representing the optional response body and subsequent `Some(...)`s for the various headers seems like a good strategy, and switching from `case Foo(value) => ... value ...` to an actual name supplier (`x1`, `x2`, ...) would eliminate the concerns around having headers named `value` and getting name conflicts.

**Comment by manuelbernhardt** [comment]
Thanks @blast-hardcheese! I will try and have a look when time permits!

**Comment by blast-hardcheese** [comment]
Thanks to @hanny24, this has been implemented for scala clients and servers!
