### ISSUE TITLE
Double inheritance of same field

### ISSUE THREAD

**Issue by tomasherman** [twilio/guardrail#538]
Consider following definition:
```yaml
swagger: '2.0'
definitions:
  Bar:
    properties:
      id:
        type: string
  Baz:
    properties:
      id:
        type: string
    required: [id]
  Foo:
    allOf:
      - $ref: "#/definitions/Bar"
      - $ref: "#/definitions/Baz"
```

Code generated is as follows:
`case class Foo(id: String, id: String)`, which is obviously not a valid Scala

I think that when two definitions are included, fields with same name should be deduplicated  if name and types are same - with rules that if either one of them is required, the result is required aswell. If both are optional, result is optional.

Do you guys agree? If yes, I will implement this fix

**Comment by kelnos** [comment]
Yes, that seems reasonable to me.
