### ISSUE TITLE
support for openapi 3.0

### ISSUE THREAD

**Issue by mikkka** [twilio/guardrail#54]
Is there support for openapi 3.0.x specification?

**Comment by blast-hardcheese** [comment]
Not currently, no. As the backing parser for guardrail is the [official parser](https://github.com/swagger-api/swagger-parser), we're limited by what they support.

It seems as though they're at `2.0.0-rc1` right now, which is exciting; if you're interested in contributing, I'd bump the `swagger-parser` dependency to that version and see what breaks.

I'd expect the changes required to be primarily in package structure and some changes to the specification files used in the tests, but the generated code should be identical once the migration has been completed.

**Comment by stanislav-chetvertkov** [comment]
just tried doing that and it does not break the build

**Comment by blast-hardcheese** [comment]
That's great! I expect there are new instances of `AbstractProperty` and other fields to check in order to support the new features, but at the very least having the new parser in place would be beneficial for those starting to switch over to the OpenAPI 3.0 spec.

**Comment by edmondo1984** [comment]
@stanislav-chetvertkov did you do any work on it?

**Comment by stanislav-chetvertkov** [comment]
@edmondo1984 After some initial examination it turned out that the 3.0 model is significantly different and switching to it affects a lot of places in the code. At the time I had very little knowledge of the codebase and decided not to do such a big change. I could give it another shot or someone else could try implementing it.

**Comment by stanislav-chetvertkov** [comment]
I'm starting to take another shot at this, hope it will work this time

**Comment by blast-hardcheese** [comment]
@stanislav-chetvertkov be aware there's a massive refactor going on in #133
