### ISSUE TITLE
Unable to access Circe's `dropNullValues` parameter

### ISSUE THREAD

**Issue by stjohnb** [twilio/guardrail#545]
I would like null values not to appear in my server's response json when they are an optional field containing a `None`. 

Circe enables this via the `dropNullValues` field in the [Printer](https://circe.github.io/circe/api/io/circe/Printer.html) class but I cannot see anyway to access this via guardrail

**Comment by kelnos** [comment]
This isn't currently supported. We're aware that our handling of required/nullable isn't correct (https://github.com/twilio/guardrail/issues/315) but don't have an ETA on a fix.

**Comment by stjohnb** [comment]
Ok, thanks for the info
