### ISSUE TITLE
Guardrail users list

### ISSUE THREAD

**Issue by tomasherman** [twilio/guardrail#563]
Hey guys.

I think it would be worth while adding a list of users (adopters) of guardrail to inspire confidence and broaden the users base.

Feel free to add Avast software where multiple teams use guardrail in production systems with http4s. Both clients and servers, even for generating event definitions from swagger  

I would also like to take this opportunity to thank you for kicking off and maintaining this project. It really was a life saver for us. And also for allowing us to make guardrail fit our needs by modifying it

**Comment by blast-hardcheese** [comment]
Tomas, thank you for your kind words, as well as everyone at Avast's contributions to the project so far.

My immediate goals for the codebase, barring bugfixes or major omissions from the current offering, are around performance optimizations and code clarity. Hopefully this will continue to motivate people to give contributing to guardrail a shot 😁
