### ISSUE TITLE
Http4s AuthedRoutes and/or middleware support

### ISSUE THREAD

**Issue by KonstantinSimeonov** [twilio/guardrail#587]
Hi, thanks for the generator! Currently, I can't find any way to generate http4s code with `AuthedRoutes` or code with support for custom middleware. I have a few questions:

- In case I'm mistaken, can you point me to an example, docs or explanations on how to do it?
- In case this is not supported, do you have any interest in supporting it?
- Would you accept a PR on that in the future?

**Comment by francescopellegrini** [comment]
See #374 and #117. I'm also really looking forward to this feature! 👍

**Comment by KonstantinSimeonov** [comment]
Thanks for the response!
