### ISSUE TITLE
How can I get request headers in generated sever's handler?

### ISSUE THREAD

**Issue by Stinger911** [twilio/guardrail#87]
I use guardrail to generate server. How can I get request headers inside handlers  routines?

**Comment by stanislav-chetvertkov** [comment]
```
trait Handler {
  def getFoo(respond: Resource.getFooResponse.type)(header: String,
                                                    longHeader: Long,
                                                    customHeader: Bar,
                                                    customOptionHeader: Option[Bar] = None,
                                                    missingCustomOptionHeader: Option[Bar] = None): scala.concurrent.Future[Resource.getFooResponse]
}
```

**Comment by stanislav-chetvertkov** [comment]
this is the server generated for https://github.com/twilio/guardrail/blob/master/modules/sample/src/main/resources/custom-header-type.yaml

**Comment by Stinger911** [comment]
Thanks a lot for quick response.
My fault, for too general question. I've meant the access to all headers (for example as Map[String, String]). But you are right, most of tasks could be solved by defining parameters in headers.

**Comment by blast-hardcheese** [comment]
This is by design; uncommunicated parameters, (even headers!) defeat the purpose of having a protocol specification.

Generated clients currently permit specifying arbitrarily headers, but this was before headers were fully supported in both clients and servers.
