### ISSUE TITLE
Integration with ScalatestRouteTest

### ISSUE THREAD

**Issue by dpblh** [twilio/guardrail#91]
Hello Guys!
I have some problem with testing generated code.

```scala
Get("/api/something") ~> router.api ~> check {
    responseAs[doSomethingResponse] shouldEqual doSomethingResponse("Service4...
}
```

error log
```
Error:(38, 19) could not find implicit value for evidence parameter of type akka.http.scaladsl.unmarshalling.FromResponseUnmarshaller[simple.module.example.server.something.SomethingResource.doSomethingResponse]
        responseAs[doSomethingResponse] shouldEqual doSomethingResponse("Service4...
```

How can I check it?
I'd like to have easy way to test generated code.
I can't see any Unmarshaller inside generated code and this is logical.

**Comment by blast-hardcheese** [comment]
I wouldn't use `doSomethingResponse` here; the `respond` object is only intended to ensure compile-time safety at the routing layer. It is completely removed at the wire protocol level; instead, `responseAs[definitions.Foo]`, though you may need to import marshallers and unmarshallers from `AkkaImplicits`.

**Comment by dpblh** [comment]
Thank you very much!
It work for me brilliantly!

**Comment by blast-hardcheese** [comment]
Glad I could be of assistance! Closing this now, please feel free to open again if anything else comes up.
